-- MySQL Script generated by MySQL Workbench
-- Вт 04 мая 2021 22:21:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mytp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mytp` ;

-- -----------------------------------------------------
-- Schema mytp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytp` ;
USE `mytp` ;

-- -----------------------------------------------------
-- Table `mytp`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Users` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Type_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Type_metrics` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Type_metrics` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Tariff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Tariff` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Tariff` (
  `id_tariff` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `price` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tariff`),
  INDEX `fk_Tariff_1_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `fk_Tariff_1`
    FOREIGN KEY (`id_type`)
    REFERENCES `mytp`.`Type_metrics` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Type_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Type_address` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Type_address` (
  `id_type_adress` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_adress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Address` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Address` (
  `id_adress` INT NOT NULL AUTO_INCREMENT,
  `id_include` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id_adress`),
  INDEX `fk_Adress_1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_Address_1_idx` (`id_include` ASC) VISIBLE,
  CONSTRAINT `fk_Adress_1`
    FOREIGN KEY (`type`)
    REFERENCES `mytp`.`Type_address` (`id_type_adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_1`
    FOREIGN KEY (`id_include`)
    REFERENCES `mytp`.`Address` (`id_adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Personal_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Personal_account` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Personal_account` (
  `id_personal_account` INT NOT NULL AUTO_INCREMENT,
  `id_adress` INT NOT NULL,
  `id_owner_user` INT NOT NULL,
  PRIMARY KEY (`id_personal_account`, `id_owner_user`),
  INDEX `fk_Personal_account_1_idx` (`id_owner_user` ASC) VISIBLE,
  CONSTRAINT `fk_Personal_account_1`
    FOREIGN KEY (`id_owner_user`)
    REFERENCES `mytp`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_account_2`
    FOREIGN KEY (`id_personal_account`)
    REFERENCES `mytp`.`Address` (`id_adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Metrics` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Metrics` (
  `id_metrics` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `id_tariff` INT NOT NULL,
  `id_personal_account` INT NOT NULL,
  `balance` DOUBLE NOT NULL,
  `prev_value` DOUBLE NOT NULL,
  `curr_value` DOUBLE NOT NULL,
  PRIMARY KEY (`id_metrics`, `id_type`, `id_tariff`, `id_personal_account`),
  INDEX `fk_Metrics_2_idx` (`id_tariff` ASC) VISIBLE,
  INDEX `fk_Metrics_1_idx` (`id_personal_account` ASC) VISIBLE,
  INDEX `fk_Metrics_3_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `fk_Metrics_1`
    FOREIGN KEY (`id_personal_account`)
    REFERENCES `mytp`.`Personal_account` (`id_personal_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Metrics_2`
    FOREIGN KEY (`id_tariff`)
    REFERENCES `mytp`.`Tariff` (`id_tariff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Metrics_3`
    FOREIGN KEY (`id_type`)
    REFERENCES `mytp`.`Type_metrics` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`User_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`User_metrics` ;

CREATE TABLE IF NOT EXISTS `mytp`.`User_metrics` (
  `id_user_metrics` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_metrics` INT NOT NULL,
  PRIMARY KEY (`id_user_metrics`, `id_metrics`),
  INDEX `fk_User_metrics_2_idx` (`id_metrics` ASC) VISIBLE,
  INDEX `fk_User_metrics_1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_User_metrics_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mytp`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_metrics_2`
    FOREIGN KEY (`id_metrics`)
    REFERENCES `mytp`.`Metrics` (`id_metrics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytp`.`Payment_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytp`.`Payment_history` ;

CREATE TABLE IF NOT EXISTS `mytp`.`Payment_history` (
  `id_payment_history` INT NOT NULL AUTO_INCREMENT,
  `id_metrics` INT NOT NULL,
  `id_user` INT NOT NULL,
  `cost` DOUBLE NOT NULL,
  `prev_value` DOUBLE NOT NULL,
  `curr_value` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_payment_history`, `id_metrics`, `id_user`),
  INDEX `fk_Check_1_idx` (`id_metrics` ASC) VISIBLE,
  INDEX `fk_Check_2_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Check_1`
    FOREIGN KEY (`id_metrics`)
    REFERENCES `mytp`.`Metrics` (`id_metrics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Check_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `mytp`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
